twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      joystick:
        topic: /joy_cmd_vel
        timeout: 0.5
        priority: 180
      keyboard:
        topic: /key_vel
        timeout: 0.5
        priority: 90
      velocity_smoother:
        topic: /cmd_vel_mux_smoothed
        timeout: 0.5
        priority: 120
      behaviour_server:
        topic: /cmd_vel_behaviour
        timeout: 0.5
        priority: 120
