twist_mux:
  ros__parameters:
    topics:
      joystick:
        topic: /joy_cmd_vel
        timeout: 0.5
        priority: 180
      keyboard:
        topic: key_vel
        timeout: 0.5
        priority: 90
      velocity_smoother:
        topic: cmd_vel_smoothed
        timeout: 0.5
        priority: 120
      behaviour_server:
        topic: cmd_vel_behaviour
        timeout: 0.5
        priority: 120