joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: /cmd_vel

      deadman_buttons: [4]

      axis_mappings:
        linear-x:
          axis: 1
          scale: 0.5
          offset: 0.0
        angular-z:
          axis: 0
          scale: 2.0
          offset: 0.0

